"""empty message

Revision ID: 00ca5f34a609
Revises: fc471fe60f7e
Create Date: 2024-08-04 14:44:46.112589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00ca5f34a609'
down_revision = 'fc471fe60f7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ebook_issued', schema=None) as batch_op:
        batch_op.add_column(sa.Column('returned', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ebook_issued', schema=None) as batch_op:
        batch_op.drop_column('returned')

    # ### end Alembic commands ###
