"""empty message

Revision ID: da3aba99ddea
Revises: 00ca5f34a609
Create Date: 2024-08-04 19:43:29.181765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da3aba99ddea'
down_revision = '00ca5f34a609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ebook', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bookurl', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ebook', schema=None) as batch_op:
        batch_op.drop_column('bookurl')

    # ### end Alembic commands ###
